### ISSUE TITLE
Bug: some display issues

### ISSUE THREAD

**Issue by hustrjh** [cumany/obsidian-floating-toc-plugin#24]
Thank you for the excellent plugin! I've encountered several issues.

## Display issues
1. When floating toc displays on the right, the levels of the titles don't display correctly. There's no indent on the right, so it's hard to recognize different levels of titles. Here're pictures below.
![image](https://user-images.githubusercontent.com/69783980/194793160-d793c89f-c50e-453d-80dd-bc5fb08f8093.png) ![image](https://user-images.githubusercontent.com/69783980/194793122-074f4123-82c7-4a04-8ade-b8236e59dff1.png)

2. Sometimes the indicator bars display like dots, I think it's not normal. It seems to occur when floating toc is set to display on the left. I didn't see that when floating toc was on the right.
![image](https://user-images.githubusercontent.com/69783980/194792943-51389418-299c-4462-8b51-fb15d30a11fe.png)

3. When I enabled text blur function, the text in reading mode didn't blur at all. So if the function only acts on preview view mode?

## Suggestion
1. I find that there is space which is a little wide to keep floating toc hover effect. Sometimes I may click on the title wrongly. So if it is OK to narrow the space or just adjust the space by the longest tile length?
![image](https://user-images.githubusercontent.com/69783980/194794234-6994172d-2430-400c-b774-f3699afc66b3.png)

**Comment by cumany** [comment]
Thank you so much for liking this plugin and for the detailed review.
1. Indentation issues will be adjusted and planned to be placed in the settings.
When the floating directory is on the right , the indent cannot be displayed because of right alignment, and can only be distinguished by the footnote h1 h2 hn. The plan is to add a new style that is still left-aligned when on the right side, which should solve this problem.
2. The higher the level, the shorter the line, and if it's a  h6 heading, it might just show up as a dot.
3.  it is a bug，will be fixed
4. I need to think about this for a while

**Comment by hustrjh** [comment]
感谢@cumany 大佬的付出~测试了下，主要bug都已经完美修复了~ 👍 
还有一些小建议：
1. 建议当工具栏位于右侧时，默认 **左对齐**，毕竟右对齐不方便查看层级。
2. 是否方便增加彩虹线或者大纲线，如果能有，那就完美啦~ 😃

**Comment by cumany** [comment]
> 感谢@cumany 大佬的付出~ 测试了下，主要bug都已经完美修复了~ 👍 还有一些小建议：
> 
> 1. 建议当工具栏位于右侧时，默认 **左对齐**，毕竟右对齐不方便查看层级。
> 2. 是否方便增加彩虹线或者大纲线，如果能有，那就完美啦~ 😃

#40

**Comment by hustrjh** [comment]
十分感谢！ 👍
